"""empty message

Revision ID: 8136ad290268
Revises: 8aea9446bf88
Create Date: 2025-07-24 06:59:35.884804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8136ad290268'
down_revision = '8aea9446bf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquilas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_granel', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquilas', schema=None) as batch_op:
        batch_op.drop_column('peso_granel')

    # ### end Alembic commands ###
