"""empty message

Revision ID: eefdbea182e7
Revises: 
Create Date: 2025-07-15 10:45:05.357748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefdbea182e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular')
    )
    op.create_table('maquilas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('esta_trillado', sa.Boolean(), nullable=True),
    sa.Column('peso_despues_trilla_kg', sa.Float(), nullable=True),
    sa.Column('grado_tostion', sa.String(length=20), nullable=True),
    sa.Column('tipo_empaque', sa.String(length=20), nullable=True),
    sa.Column('porcentaje_merma', sa.Float(), nullable=True),
    sa.Column('precio_total', sa.Float(), nullable=True),
    sa.Column('detalle_precio', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maquilas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maquilas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquilas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maquilas_id'))

    op.drop_table('maquilas')
    op.drop_table('clientes')
    op.drop_table('users')
    # ### end Alembic commands ###
