"""empty message

Revision ID: ffe64a19d9e8
Revises: e35e983d1374
Create Date: 2025-07-17 10:51:44.730902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe64a19d9e8'
down_revision = 'e35e983d1374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquilas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario_empaque', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquilas', schema=None) as batch_op:
        batch_op.drop_column('precio_unitario_empaque')

    # ### end Alembic commands ###
